export const BOOKING_ERROR_CODES = {
  NON_WEEKDAY_BOOKING: 'NON_WEEKDAY_BOOKING',
  OUTSIDE_BUSINESS_HOURS: 'OUTSIDE_BUSINESS_HOURS',
  HOLIDAY_CLOSURE: 'HOLIDAY_CLOSURE',
  WORKER_UNAVAILABLE: 'WORKER_UNAVAILABLE',
  INVALID_TIMESTAMP_FORMAT: 'INVALID_TIMESTAMP_FORMAT',
  PAST_BOOKING_TIME: 'PAST_BOOKING_TIME',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
};
